Developer
AnastasiaOsinska/TodoApp pull request #2
Opened 2020-11-26 15:37 UTC by AnastasiaOsinska

2020-11-27 05:28 UTC, vadimux commented
branch should be named `dev` or `development` not `Developer` and `main` branch is `master` as well

2020-11-27 05:40 UTC, vadimux commented
>  Your project does not explicitly specify the CocoaPods master specs repo. Since CDN is now used as the default, you may safely remove it from your repos directory via `pod repo remove master`. To suppress this warning please add `warn_for_unused_master_specs_repo => false` to your Podfile.

you need to remove it as done in VKMarket

2020-11-27 05:42 UTC, vadimux commented
can't build the project -

> error: Build input files cannot be found: '/Users/_.com/TodoApp/TodoApp/Extensions/SimpleOver.swift', '/Users/_.com/TodoApp/TodoApp/UIComponents/SideMenu.swift' (in target 'TodoApp' from project 'TodoApp')

2020-11-27 05:47 UTC, vadimux commented
as I see there are no files SimpleOver.swift and SideMenu.swift

2020-11-27 05:47 UTC, vadimux requested changes

2020-11-27 05:47 UTC, vadimux commented on Podfile
> +pod 'SideMenu'
please add an indent

2020-11-27 05:47 UTC, vadimux commented on Podfile
> +# platform :ios, '9.0'
usually specifies the minimum version for pods

2020-11-27 05:47 UTC, vadimux commented on Podfile
> +# Uncomment the next line to define a global platform for your project
first line usually is `source 'https://github.com/CocoaPods/Specs.git'`

2020-11-27 05:47 UTC, vadimux commented on Resources/AppDelegate.swift
> +//        window = UIWindow()
commented lines should not go into the commit

2020-11-27 05:47 UTC, vadimux commented on TodoApp/Controllers/ContainerController.swift
> +class ContainerController: UIViewController, MenuControllerDelegate {
`MenuControllerDelegate` should be as extension

2020-11-27 05:47 UTC, vadimux commented on TodoApp/Controllers/ContainerController.swift
> +        1
add `return` - it's in the style of methods that return something

2020-11-27 05:47 UTC, vadimux commented on TodoApp/Controllers/NewTaskController.swift
> +        let titleLabel = UILabel(frame: CGRect(x: 0, y: 0, width: view.frame.width - 10, height: view.frame.height))
setting of UI - better put into a separate method

2020-11-27 05:47 UTC, vadimux commented on TodoApp/Controllers/NewTaskController.swift
> +
is an empty string needed here if the previous method doesn't have it?

2020-11-27 05:47 UTC, vadimux commented on TodoApp/Controllers/SettingsViewController/SettingsViewController.swift
> +class SettingsViewController: UIViewController, UITableViewDelegate, UITableViewDataSource {
`UITableViewDelegate, UITableViewDataSource` as extension

2020-11-27 05:47 UTC, vadimux commented on TodoApp/Controllers/TasksTableViewCell/TasksTableViewCell.swift
> +    var parentViewController: UIViewController? {
not sure that we should use this, but need check with app..I'll add the comment in the future about it

2020-11-30 09:07 UTC, AnastasiaOsinska commented on Podfile
> +# platform :ios, '9.0'
solved

2020-11-30 09:10 UTC, AnastasiaOsinska commented on Podfile
> +# Uncomment the next line to define a global platform for your project
solved

2020-11-30 09:10 UTC, AnastasiaOsinska commented on Resources/AppDelegate.swift
> +//        window = UIWindow()
solved

2020-11-30 09:14 UTC, AnastasiaOsinska commented on TodoApp/Controllers/ContainerController.swift
> +class ContainerController: UIViewController, MenuControllerDelegate {
solved

2020-11-30 09:14 UTC, AnastasiaOsinska commented on TodoApp/Controllers/ContainerController.swift
> +        1
done

2020-11-30 09:17 UTC, AnastasiaOsinska commented on TodoApp/Controllers/NewTaskController.swift
> +
solved

2020-11-30 09:19 UTC, AnastasiaOsinska commented on TodoApp/Controllers/SettingsViewController/SettingsViewController.swift
> +class SettingsViewController: UIViewController, UITableViewDelegate, UITableViewDataSource {
solved

2020-11-30 16:50 UTC, AnastasiaOsinska commented on TodoApp/Controllers/TasksTableViewCell/TasksTableViewCell.swift
> +    var parentViewController: UIViewController? {
removed

2020-12-01 09:03 UTC, closed without merging