made floating NewtaskButton, added task edition, added Initial list o…
AnastasiaOsinska/TodoApp pull request #4
Opened 2020-12-01 14:55 UTC by AnastasiaOsinska

…f 15 tasks randomly generated

2020-12-02 05:51 UTC, vadimux commented on TodoApp/Controllers/ContainerController.swift
> +        addNewTaskButton.isUserInteractionEnabled = true
I guess you can remove this line

2020-12-02 05:55 UTC, vadimux commented on TodoApp/Controllers/SettingsViewController/SettingsViewController.swift
> +    let data = ["Memory","Preferences", "SQLite database", "Core Data", "File"]
need a space before `"Preferences"`

2020-12-02 05:56 UTC, vadimux commented on TodoApp/Controllers/ContainerController.swift
> -
usually such changes are not added to the history (in the commit). I mean to remove/add empty lines

2020-12-02 05:57 UTC, vadimux commented on TodoApp/Controllers/ContainerController.swift
> +                self.addNewTaskButton.transform = .identity
`[weak self] in` need to add, because there is `self.addNewTaskButton` in closure

2020-12-02 09:46 UTC, AnastasiaOsinska commented on TodoApp/Controllers/ContainerController.swift
> +        addNewTaskButton.isUserInteractionEnabled = true
done

2020-12-02 09:46 UTC, AnastasiaOsinska commented on TodoApp/Controllers/SettingsViewController/SettingsViewController.swift
> +    let data = ["Memory","Preferences", "SQLite database", "Core Data", "File"]
done

2020-12-02 09:46 UTC, AnastasiaOsinska commented on TodoApp/Controllers/ContainerController.swift
> -
got it

2020-12-02 09:53 UTC, AnastasiaOsinska commented on TodoApp/Controllers/ContainerController.swift
> +                self.addNewTaskButton.transform = .identity
done

2020-12-04 13:23 UTC, vadimux commented on TodoApp/LoaderView/LoadingView.swift
> +    var spinner : UIView?
extra space after spinner

2020-12-04 13:24 UTC, vadimux commented on TodoApp/LoaderView/LoadingView.swift
> +    func showSpinner(onView : UIView) {
extra space after `onView`

2020-12-04 13:26 UTC, vadimux commented on TodoApp/LoaderView/LoadingView.swift
> +class LoaderView: UIViewController {
why did we inherit from `UIViewController`?

2020-12-04 13:27 UTC, vadimux commented on TodoApp/LoaderView/LoadingView.swift
> +    static let shared = LoaderView()
singleton for Loader? My recommendation is to think of other implementation options..

2020-12-04 13:34 UTC, vadimux requested changes

2020-12-04 13:34 UTC, vadimux commented on TodoApp/Controllers/ContainerController.swift
> +        self.present(popupDialog, animated: true, completion: nil)
well..classic crash on iPad (I also went through this) - check it and it's good caught crash for the future:)

2020-12-05 17:30 UTC, AnastasiaOsinska commented on TodoApp/LoaderView/LoadingView.swift
> +    static let shared = LoaderView()
solved

2020-12-05 17:31 UTC, AnastasiaOsinska commented on TodoApp/LoaderView/LoadingView.swift
> +    func showSpinner(onView : UIView) {
solved

2020-12-05 17:31 UTC, AnastasiaOsinska commented on TodoApp/LoaderView/LoadingView.swift
> +class LoaderView: UIViewController {
solved

2020-12-05 17:31 UTC, AnastasiaOsinska commented on TodoApp/LoaderView/LoadingView.swift
> +    var spinner : UIView?
done

2020-12-05 19:13 UTC, AnastasiaOsinska commented on TodoApp/Controllers/ContainerController.swift
> +        self.present(popupDialog, animated: true, completion: nil)
solved

2020-12-07 14:16 UTC, vadimux requested changes

2020-12-07 14:16 UTC, vadimux commented on TodoApp/Controllers/ContainerController.swift
> +        switch filter {
first step for refactoring is
```
        newTaskViewController.completion = {
            switch filter {
            case .all, .none:
                return { [weak self] todo in
                    self?.task.insert(todo, at: 0)
                    self?.saveData()
                    self?.tableView.reloadData()
                }
            case .priority:
                return { [weak self] todo in
                    self?.task.append(todo)
                    todo.isFavourite = true
                    self?.saveData()
                    self?.tableView.reloadData()
                }
            }
        }()
```

2020-12-07 14:16 UTC, vadimux commented on TodoApp/Controllers/ContainerController.swift
> +
extra line

2020-12-07 14:16 UTC, vadimux commented on TodoApp/Controllers/SettingsTableViewCell/SettingsTableViewCell.swift
> +        guard let buttonCheck = buttonCheck else { return }
I guess don't need use `guard`. Enough 
```
    @IBAction func checkMarkButtonAction(_ sender: Any) {
        buttonCheck?()
    }
```

2020-12-08 10:22 UTC, AnastasiaOsinska commented on TodoApp/CheckButton/CheckButton.swift
> +            if isChecked {
solved

2020-12-08 10:24 UTC, AnastasiaOsinska commented on TodoApp/Controllers/ContainerController.swift
> +        switch filter {
done

2020-12-08 10:25 UTC, AnastasiaOsinska commented on TodoApp/LoaderView/LoadingView.swift
> +    var spinner : UIView?
done

2020-12-09 06:31 UTC, vadimux requested changes

2020-12-09 06:34 UTC, merged