CoreDataStack
AnastasiaOsinska/TodoApp pull request #5
Opened 2020-12-09 11:21 UTC by AnastasiaOsinska

2020-12-09 12:25 UTC, vadimux requested changes

2020-12-09 12:25 UTC, vadimux commented on ToDo+CoreDataProperties.swift
> +//  ToDo+CoreDataProperties.swift
we should remove this file

2020-12-09 12:25 UTC, vadimux commented on ToDo+CoreDataClass.swift
> +//  ToDo+CoreDataClass.swift
we should remove this file and select codeGenerationType="class" for CoreData Entity

2020-12-09 12:25 UTC, vadimux commented on TodoApp/DataProvider/CoreDataManager.swift
> +                    let managedObjectData:NSManagedObject = managedObject as! NSManagedObject
I don't recommend use force unwrapping for this

2020-12-09 12:25 UTC, vadimux commented on TodoApp/DataProvider/CoreDataManager.swift
> +        switch type {
is this `switch` really needed here?

2020-12-09 12:25 UTC, vadimux commented on Resources/AppDelegate.swift
> -
such changes should not be committed

2020-12-09 12:25 UTC, vadimux commented on TodoApp/DataProvider/CoreDataManager.swift
> +        container.loadPersistentStores(completionHandler: {
if the `completionHandler` has the last position - we can omit it

2020-12-09 12:25 UTC, vadimux commented on TodoApp/DataProvider/CoreDataManager.swift
> +        var allTableDataArray : [ToDo] = [ToDo]()
extra space before colon

2020-12-09 12:25 UTC, vadimux commented on TodoApp/DataProvider/CoreDataManager.swift
> +            var newTodos = [Todo]()
the same names for classes are very inconvenient, maybe we should think about a different naming?

2020-12-10 09:52 UTC, AnastasiaOsinska commented on ToDo+CoreDataClass.swift
> +//  ToDo+CoreDataClass.swift
done

2020-12-10 09:56 UTC, AnastasiaOsinska commented on TodoApp/DataProvider/CoreDataManager.swift
> +                    let managedObjectData:NSManagedObject = managedObject as! NSManagedObject
done

2020-12-10 13:08 UTC, merged